### ISSUE TITLE
[FEATURE] Add soundcloud

### ISSUE THREAD

**Issue by alefvanoon** [TheDavidDelta/kainet-music#9]
It would be great if we can use soundcloud.com over kainet-music. :)

**Comment by thedaviddelta** [comment]
Sorry, I don't see this happening.
Kainet isn't oriented to be a multi-frontend of multiple services but a Spotify alternative, using YTMusic for scraping official songs as they have a very similar catalog. Soundcloud doesn't even have "official" songs, but only the ones every user uploads, just like standard YouTube.
In addition, I'm not aware of any privacy problem with Soundcloud.

Regards, David.
